baseURL = "https://ostring.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of OString"
publishDir = "docs"

# theme as hugo module
# theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

[params]
author = "OString"
description = "Welcome to OString's Website"
profilePicture = "images/profile.jpg"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "DataCenter"
    url = "/posts/data_center/"
    weight = 2
  [[menu.main]]
    name = "TechNews"
    url = "/posts/tech_news/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[frontmatter]
  title = ["title", "h1"]  # Use front matter title first, then h1 title
  date = ["date", ":fileModTime"]  # Use file modification time as date

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[services]
# Enable Disqus.Disqus.Shortname
  [services.disqus]
    #shortname = 'your-disqus-shortname'
# Google Analytics
  [services.googleAnalytics]
    #ID = 'G-MEASUREMENT_ID'
